# Generated by Django 5.2.8 on 2025-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement_created',
            field=models.BooleanField(default=False),
        ),
    ]
