# Generated by Django 5.2.8 on 2025-11-21 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('ifsc', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_settlement', models.BooleanField(default=True)),
                ('settlement_cycle', models.CharField(choices=[('T+1', 'T+1'), ('T+2', 'T+2'), ('INSTANT', 'INSTANT')], default='T+1', max_length=10)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_sms', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='merchants.merchant')),
            ],
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['phone'], name='merchants_m_phone_00a594_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['created_at'], name='merchants_m_created_c2ecef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantbankaccount',
            unique_together={('merchant', 'account_number')},
        ),
    ]
