# Generated by Django 5.2.8 on 2025-12-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_couponphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponphone',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
