# Generated by Django 5.2.8 on 2025-12-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_couponphone_phone'),
        ('payments', '0002_payment_settlement_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='payments.payment')),
            ],
            options={
                'unique_together': {('coupon', 'phone')},
            },
        ),
    ]
